/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/Administrator.PC-20190811NNTS/Desktop/AHB_FPGA256_CC/al_ip/M3WithAHB.v
 ** Date	:	2019 10 15
 ** TD version	:	4.5.12562
\************************************************************/

`timescale 1ns / 1ps

module M3WithAHB ( ppm_clk,
	h2h_haddr,
	h2h_htrans,
	h2h_hwrite,
	h2h_hsize,
	h2h_hburst,
	h2h_hprot,
	h2h_hwdata,
	h2h_hrdata,
	h2h_hreadyout,
	h2h_hresp,
	h2h_mclk,
	h2h_rstn );

	output	[31:0]	h2h_haddr;
	output	[1:0]	h2h_htrans;
	output	h2h_hwrite;
	output	[2:0]	h2h_hsize;
	output	[2:0]	h2h_hburst;
	output	[3:0]	h2h_hprot;
	output	[31:0]	h2h_hwdata;
	input	[31:0]	h2h_hrdata;
	input	h2h_hreadyout;
	input	[1:0]	h2h_hresp;
	input	h2h_mclk;
	input	h2h_rstn;
	input	ppm_clk;
	EF2_PHY_MCU #(
		.GPIO_L0("ENABLE"),
		.GPIO_L1("ENABLE"),
		.GPIO_L8("ENABLE"),
		.GPIO_L9("ENABLE"))
	mcu_inst(
		.ppm_clk(ppm_clk),
		.h2h_haddr(h2h_haddr),
		.h2h_htrans(h2h_htrans),
		.h2h_hwrite(h2h_hwrite),
		.h2h_hsize(h2h_hsize),
		.h2h_hburst(h2h_hburst),
		.h2h_hprot(h2h_hprot),
		.h2h_hwdata(h2h_hwdata),
		.h2h_hrdata(h2h_hrdata),
		.h2h_hreadyout(h2h_hreadyout),
		.h2h_hresp(h2h_hresp),
		.h2h_mclk(h2h_mclk),
		.h2h_rstn(h2h_rstn),
		.gpio_h_out({open,open,open,open,open,open,open,open,open,open,open,open,open,open,open,open}),
		.gpio_h_oe_n({open,open,open,open,open,open,open,open,open,open,open,open,open,open,open,open}),
		.gpio_h_in({1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0}));
endmodule